// scraper/seed.js
import 'dotenv/config';
import mongoose from 'mongoose';
import Company from '../src/models/Company.model.js';
import ScraperConfig from '../src/models/ScraperConfig.model.js';

await mongoose.connect(process.env.MONGO_URI);

const companies = [
    // Premium tier
    { name: 'Google', tier: 'premium' },
    { name: 'Microsoft', tier: 'premium' },
    { name: 'Apple', tier: 'premium' },
    { name: 'Meta', tier: 'premium' },
    { name: 'Amazon', tier: 'premium' },
    { name: 'Netflix', tier: 'premium' },
    { name: 'Atlassian', tier: 'premium' },
    { name: 'Stripe', tier: 'premium' },
    { name: 'Salesforce', tier: 'premium' },
    { name: 'Adobe', tier: 'premium' },
    { name: 'Intuit', tier: 'premium' },
    { name: 'DeShaw', tier: 'premium' },
    { name: 'Rubrik', tier: 'premium' },
    { name: 'Coinbase', tier: 'premium' },
    { name: 'Confluent', tier: 'premium' },
    { name: 'Coupang', tier: 'premium' },
    { name: 'Datadog', tier: 'premium' },
    { name: 'Figma', tier: 'premium' },
    { name: 'Goldman Sachs', tier: 'premium' },
    { name: 'JP Morgan Chase', tier: 'premium' },
    { name: 'Visa', tier: 'premium' },
    { name: 'Cisco', tier: 'premium' },
    { name: 'Intel', tier: 'premium' },
    { name: 'Warner Bros Discovery', tier: 'premium' },
    { name: 'AMD', tier: 'premium' },
    { name: 'Oracle', tier: 'premium' },
    { name: 'American Express', tier: 'premium' },
    { name: 'Twitter', tier: 'premium' },
    { name: 'Uber', tier: 'premium' },
    { name: 'Airbnb', tier: 'premium' },
    { name: 'Lyft', tier: 'premium' },
    { name: 'Palantir', tier: 'premium' },
    { name: 'Snowflake', tier: 'premium' },
    { name: 'MongoDB', tier: 'premium' },
    { name: 'Twilio', tier: 'premium' },
    { name: 'Cloudflare', tier: 'premium' },
    { name: 'Palo Alto Networks', tier: 'premium' },
    { name: 'CrowdStrike', tier: 'premium' },
    { name: 'ServiceNow', tier: 'premium' },
    { name: 'Workday', tier: 'premium' },
    { name: 'Splunk', tier: 'premium' },
    { name: 'HashiCorp', tier: 'premium' },
    { name: 'Okta', tier: 'premium' },
    { name: 'Zscaler', tier: 'premium' },
    { name: 'Elastic', tier: 'premium' },
    { name: 'Instacart', tier: 'premium' },
    { name: 'DoorDash', tier: 'premium' },
    { name: 'Robinhood', tier: 'premium' },
    { name: 'Asana', tier: 'premium' },
    { name: 'Dropbox', tier: 'premium' },
    { name: 'Box', tier: 'premium' },
    { name: 'Slack', tier: 'premium' },
    { name: 'Zoom', tier: 'premium' },
    { name: 'Shopify', tier: 'premium' },
    { name: 'Square', tier: 'premium' },
    { name: 'Block', tier: 'premium' },
    { name: 'PayPal', tier: 'premium' },
    { name: 'Grab', tier: 'premium' },
    { name: 'Sea Limited', tier: 'premium' },
    { name: 'ByteDance', tier: 'premium' },
    { name: 'Samsung', tier: 'premium' },
    { name: 'Sony', tier: 'premium' },
    { name: 'SAP', tier: 'premium' },

    // Startup tier
    { name: 'Razorpay', tier: 'startup' },
    { name: 'Zepto', tier: 'startup' },
    { name: 'Groww', tier: 'startup' },
    { name: 'CRED', tier: 'startup' },
    { name: 'Slice', tier: 'startup' },
    { name: 'BrowserStack', tier: 'startup' },
    { name: 'Chargebee', tier: 'startup' },
    { name: 'Hasura', tier: 'startup' },
    { name: 'Setu', tier: 'startup' },
    { name: 'Niyo', tier: 'startup' },
    { name: 'Jupiter', tier: 'startup' },
    { name: 'Smallcase', tier: 'startup' },
    { name: 'Darwinbox', tier: 'startup' },
    { name: 'Leadsquared', tier: 'startup' },
    { name: 'Clevertap', tier: 'startup' },
    { name: 'MoEngage', tier: 'startup' },
    { name: 'Wingify', tier: 'startup' },
    { name: 'Lenskart', tier: 'startup' },
    { name: 'Spinny', tier: 'startup' },
    { name: 'Cars24', tier: 'startup' },
    { name: 'Oyo', tier: 'startup' },
    { name: 'Ola', tier: 'startup' },
    { name: 'Dunzo', tier: 'startup' },
    { name: 'Blinkit', tier: 'startup' },
    { name: 'Delhivery', tier: 'startup' },
    { name: 'Shiprocket', tier: 'startup' },
    { name: 'Browserless', tier: 'startup' },
    { name: 'Sarvam AI', tier: 'startup' },
    { name: 'Krutrim', tier: 'startup' },
    { name: 'Mira', tier: 'startup' },

    // Good tier
    { name: 'Postman', tier: 'good' },
    { name: 'Databricks', tier: 'good' },
    { name: 'VMware', tier: 'good' },
    { name: 'LinkedIn', tier: 'good' },
    { name: 'Rippling', tier: 'good' },
    { name: 'Hubspot', tier: 'good' },
    { name: 'UiPath', tier: 'good' },
    { name: 'Akamai', tier: 'good' },
    { name: 'Arcesium', tier: 'good' },
    { name: 'Zalando', tier: 'good' },
    { name: 'Meesho', tier: 'good' },
    { name: 'Siemens', tier: 'good' },
    { name: 'Teradata', tier: 'good' },
    { name: 'NVIDIA', tier: 'good' },
    { name: 'Wells Fargo', tier: 'good' },
    { name: 'Electronic Arts', tier: 'good' },
    { name: 'Amazon Web Services', tier: 'good' },
    { name: 'LSEG', tier: 'good' },
    { name: 'Qualcomm', tier: 'good' },
    { name: 'Freshworks', tier: 'good' },
    { name: 'Notion', tier: 'good' },
    { name: 'Urban Company', tier: 'good' },
    { name: 'Swiggy', tier: 'good' },
    { name: 'Zomato', tier: 'good' },
    { name: 'Flipkart', tier: 'good' },
    { name: 'Myntra', tier: 'good' },
    { name: 'Nykaa', tier: 'good' },
    { name: 'Paytm', tier: 'good' },
    { name: 'PhonePe', tier: 'good' },
    { name: 'Upstox', tier: 'good' },
    { name: 'Zerodha', tier: 'good' },
    { name: 'Turing', tier: 'good' },
    { name: 'Verizon', tier: 'good' },
    { name: 'Toptal', tier: 'good' },
    { name: 'PwC', tier: 'good' },
    { name: 'EY', tier: 'good' },
    { name: 'Deloitte', tier: 'good' },
    { name: 'KPMG', tier: 'good' },
    { name: 'Walmart', tier: 'good' },
    { name: 'A.P. Moller - Maersk', tier: 'good' },
    { name: 'Securonix', tier: 'good' },
    { name: 'Nike', tier: 'good' },
    { name: 'Nutanix', tier: 'good' },
    { name: 'Societe Generale Global Solution Centre', tier: 'good' },
    { name: 'Accenture', tier: 'good' },
    { name: 'IBM', tier: 'good' },
    { name: 'Capgemini', tier: 'good' },
    { name: 'Thoughtworks', tier: 'good' },
    { name: 'Publicis Sapient', tier: 'good' },
    { name: 'GlobalLogic', tier: 'good' },
    { name: 'Nagarro', tier: 'good' },
    { name: 'Mphasis', tier: 'good' },
    { name: 'Persistent Systems', tier: 'good' },
    { name: 'Coforge', tier: 'good' },
    { name: 'Hexaware', tier: 'good' },
    { name: 'Zendesk', tier: 'good' },
    { name: 'Sprinklr', tier: 'good' },
    { name: 'Gartner', tier: 'good' },
    { name: 'Nielsen', tier: 'good' },
    { name: 'Mastercard', tier: 'good' },
    { name: 'Fidelity', tier: 'good' },
    { name: 'Morgan Stanley', tier: 'good' },
    { name: 'Deutsche Bank', tier: 'good' },
    { name: 'Barclays', tier: 'good' },
    { name: 'HSBC', tier: 'good' },
    { name: 'Standard Chartered', tier: 'good' },
    { name: 'BNY Mellon', tier: 'good' },
    { name: 'State Street', tier: 'good' },
    { name: 'Publicis', tier: 'good' },
    { name: 'Xoriant', tier: 'good' },
    { name: 'Tekion', tier: 'good' },
    { name: 'Cimpress', tier: 'good' },
    { name: 'Accedian', tier: 'good' },
    { name: 'Razorthink', tier: 'good' },
    { name: 'InMobi', tier: 'good' },
    { name: 'Unacademy', tier: 'good' },
    { name: 'Byju', tier: 'good' },
    { name: 'Physics Wallah', tier: 'good' },
    { name: 'Vedantu', tier: 'good' },
    { name: 'Udaan', tier: 'good' },
    { name: 'Shadowfax', tier: 'good' },
    { name: 'Porter', tier: 'good' },
    { name: 'Rapido', tier: 'good' },
    { name: 'Navi', tier: 'good' },
    { name: 'Pine Labs', tier: 'good' },
    { name: 'Juspay', tier: 'good' },
    { name: 'Cashfree', tier: 'good' },
    { name: 'Setu', tier: 'good' },
    { name: 'Open Financial', tier: 'good' },
    { name: 'Khatabook', tier: 'good' },
    { name: 'OkCredit', tier: 'good' },
    { name: 'Bharatpe', tier: 'good' },
    { name: 'Mswipe', tier: 'good' },
    { name: 'Innovaccer', tier: 'good' },
    { name: 'Healthifyme', tier: 'good' },
    { name: 'Practo', tier: 'good' },
    { name: 'Pharmeasy', tier: 'good' },
    { name: 'Cure.fit', tier: 'good' },
    { name: 'Pristyn Care', tier: 'good' },
];

await Company.bulkWrite(
    companies.map(c => ({
        updateOne: {
            filter: { name: c.name },
            update: { $set: c },
            upsert: true,
        },
    }))
);
console.log(`Upserted ${companies.length} companies`);

await ScraperConfig.findOneAndUpdate(
    { isActive: true },
    {
        keywords: [
            'software engineer OR backend engineer OR software developer',
            'fullstack developer OR frontend developer',
            'SDE 1 OR SDE 2',
        ],
        isActive: true,
        webScraper: {
            maxPages: 2,
            maxAgeDays: 2,
        },
    },
    { upsert: true, returnDocument: 'after' }
);
console.log('Scraper config upserted');

await mongoose.disconnect();
process.exit(0);